#!/bin/sh
# aerc filter which runs w3m using socksify (from the dante package) to prevent
# any phoning home by rendered emails. If socksify is not installed then w3m is
# used without it.
if [ $(command -v socksify) ]; then
	export SOCKS_SERVER="127.0.0.1:1"
	PRE_CMD=socksify
else
	PRE_CMD=""
fi
exec $PRE_CMD w3m \
	-I UTF-8 \
	-T text/html \
	-cols $(tput cols) \
	-dump \
	-o display_image=false \
	-o display_link_number=true
